function [COMBColumn, COMBPile, COMBSoil, SOLO]=combinacao(PORTICO, DADOS, MOMENTO, NORMAL, PILAR, ESTRUTURAL, TRANSX)
% -------------------------------------------------------------------------
% UNIVERSIDADE FEDERAL DE PERNAMBUCO   - CENTRO DE TECNOLOGIA E GEOCIÊNCIAS
% PROGRAMA DE PÓS-GRADUAÇÃO EM ENGENHARIA CIVIL        - ÁREA DE ESTRUTURAS
%
% TESE DE DOUTORADO
% MODELOS  DE SELEÇÃO DE  MÉDIA FIDELIDADE  PARA  ANÁLISE DE  INCERTEZAS EM
% ESTRUTURAS DE CONCRETO ARMADO.
% ALUNO       Sérgio José Priori Jovino Marques Filho
% ORIENTADOR  Prof. Ézio da Rocha Araújo
% -------------------------------------------------------------------------
% DESCRIÇÃO
% Rotina para determinação realizar as combinações de carga. duas situações
% serão abordadas:
% COMBalong - considerar-se-a o alongamento da ponte: PP+SC+TempPOS
% COMBenc - considerar-se-a o encurtamento da ponte: PP+SC+TempNEG+TD
% -------------------------------------------------------------------------
% MODIFICAÇÕES:         
%--------------------------------------------------------------------------
% VARIÁVEIS DE ENTRADA: --
% VARIÁVEIS DE SAÍDA:   PILARin: "structure" contendo as variáveis necessá-
% rias ao algoritmo de detalhamento do pilar - column.m 
%--------------------------------------------------------------------------
% CRIADA EM 02-agosto-2017
% -------------------------------------------------------------------------

COMBPile=0;
% CÁLCULO DOS ESFORÇOS INTERNOS ATUANTES NOS ELEMENTOS ESTRUTURAIS
% Pilar
[PILAR]=columnIntEff(MOMENTO, NORMAL, DADOS, ESTRUTURAL, PILAR);

% ESPECIFICAMNTE PARA O CASO DA OTIMIZAÇÃO UTILIZANDO O SPSA NÃO SERÁ
% REALIZADA A COMBINAÇÃO DE CARGA PARA O CASO DA ESTACA, HAJA VISTA QUE ELA
% NÃO IRÁ "PARTICIPAR" DO PROCESSO.
% Estaca
% [ESTACA]=pileIntEff(DADOS, MOMENTO, NORMAL, ESTRUTURAL);
% Solo
[SOLO]=soildispl(TRANSX, DADOS, ESTRUTURAL,PORTICO);

% COMBINAÇÕES
% Serão criadas 24 combinações diferentes conforme listagem abaixo. Os
% esforços internos de cada combinação serão armazenados
% na matriz COMBIntEff, onde a primeira coluna irá conter o valor do momento
% fletor, a segunda couna o esfornço normal e por fim a terceira o
% deslocamento no topo do encontro. Os deslocamentos serão armazenados na
% matriz COMBDisp, que conterá 24 linhas e "n" colunas, onde "n" é a
% quantidade de nós na estaca + enocntro.
%-------------------------------------------------------------------------%
% COMB1=PP+EMPSOLO+TempNEG
% COMB2=PP+EMPSOLO+TempNEG+TREMTIPO
% COMB3=PP+EMPSOLO+TempNEG+TD
% COMB4=PP+EMPSOLO+TempNEG+TD+TREMTIPO
% COMB5=PP+EMPSOLO
% COMB6=PP+EMPSOLO+TREMTIPO
% COMB7=PP+EMPSOLO+TD
% COMB8=PP+EMPSOLO+TD+TREMTIPO
% COMB9=PP+TempPOS
% COMB10=PP+TempPOS+TREMTIPO
% COMB11=PP+TempPOS+TD
% COMB12=PP+TempPOS+TD+TREMTIPO

% Pilar
COMBColumn(:,:,1)=[PILAR.NPP+PILAR.NEMPSOLO+PILAR.NTempNEG, PILAR.MPP+PILAR.MEMPSOLO+PILAR.MTempNEG];
COMBColumn(:,:,2)=[PILAR.NPP+PILAR.NEMPSOLO+PILAR.NTempNEG+PILAR.NTREMTIPO, PILAR.MPP+PILAR.MEMPSOLO+PILAR.MTempNEG+PILAR.MTREMTIPO];
COMBColumn(:,:,3)=[PILAR.NPP+PILAR.NEMPSOLO+PILAR.NTempNEG+PILAR.NTD, PILAR.MPP+PILAR.MEMPSOLO+PILAR.MTempNEG+PILAR.MTD];
COMBColumn(:,:,4)=[PILAR.NPP+PILAR.NEMPSOLO+PILAR.NTempNEG+PILAR.NTD+PILAR.NTREMTIPO, PILAR.MPP+PILAR.MEMPSOLO+PILAR.MTempNEG+PILAR.MTD+PILAR.MTREMTIPO];
COMBColumn(:,:,5)=[PILAR.NPP+PILAR.NEMPSOLO, PILAR.MPP+PILAR.MEMPSOLO];
COMBColumn(:,:,6)=[PILAR.NPP+PILAR.NEMPSOLO+PILAR.NTREMTIPO, PILAR.MPP+PILAR.MEMPSOLO+PILAR.MTREMTIPO];
COMBColumn(:,:,7)=[PILAR.NPP+PILAR.NEMPSOLO+PILAR.NTD, PILAR.MPP+PILAR.MEMPSOLO+PILAR.MTD];
COMBColumn(:,:,8)=[PILAR.NPP+PILAR.NEMPSOLO+PILAR.NTD+PILAR.NTREMTIPO, PILAR.MPP+PILAR.MEMPSOLO+PILAR.MTD+PILAR.MTREMTIPO];
COMBColumn(:,:,9)=[PILAR.NPP+PILAR.NTempPOS, PILAR.MPP+PILAR.MTempPOS];
COMBColumn(:,:,10)=[PILAR.NPP+PILAR.NTempPOS+PILAR.NTREMTIPO, PILAR.MPP+PILAR.MTempPOS+PILAR.MTREMTIPO];
COMBColumn(:,:,11)=[PILAR.NPP+PILAR.NTempPOS+PILAR.NTD, PILAR.MPP+PILAR.MTempPOS+PILAR.MTD];
COMBColumn(:,:,12)=[PILAR.NPP+PILAR.NTempPOS+PILAR.NTD+PILAR.NTREMTIPO, PILAR.MPP+PILAR.MTempPOS+PILAR.MTD+PILAR.MTREMTIPO];

% ESTACA NÃO PARTICIPA DO PROCESSO DE OTIMIZAÇÃO
% % Estaca
% COMBPile(:,:,1)=[ESTACA.NPP+ESTACA.NEMPSOLO+ESTACA.NTempNEG, ESTACA.MPP+ESTACA.MEMPSOLO+ESTACA.MTempNEG];
% COMBPile(:,:,2)=[ESTACA.NPP+ESTACA.NEMPSOLO+ESTACA.NTempNEG+ESTACA.NTREMTIPO, ESTACA.MPP+ESTACA.MEMPSOLO+ESTACA.MTempNEG+ESTACA.MTREMTIPO];
% COMBPile(:,:,3)=[ESTACA.NPP+ESTACA.NEMPSOLO+ESTACA.NTempNEG+ESTACA.NTD, ESTACA.MPP+ESTACA.MEMPSOLO+ESTACA.MTempNEG+ESTACA.MTD];
% COMBPile(:,:,4)=[ESTACA.NPP+ESTACA.NEMPSOLO+ESTACA.NTempNEG+ESTACA.NTD+ESTACA.NTREMTIPO, ESTACA.MPP+ESTACA.MEMPSOLO+ESTACA.MTempNEG+ESTACA.MTD+ESTACA.MTREMTIPO];
% COMBPile(:,:,5)=[ESTACA.NPP+ESTACA.NEMPSOLO, ESTACA.MPP+ESTACA.MEMPSOLO];
% COMBPile(:,:,6)=[ESTACA.NPP+ESTACA.NEMPSOLO+ESTACA.NTREMTIPO, ESTACA.MPP+ESTACA.MEMPSOLO+ESTACA.MTREMTIPO];
% COMBPile(:,:,7)=[ESTACA.NPP+ESTACA.NEMPSOLO+ESTACA.NTD, ESTACA.MPP+ESTACA.MEMPSOLO+ESTACA.MTD];
% COMBPile(:,:,8)=[ESTACA.NPP+ESTACA.NEMPSOLO+ESTACA.NTD+ESTACA.NTREMTIPO, ESTACA.MPP+ESTACA.MEMPSOLO+ESTACA.MTD+ESTACA.MTREMTIPO];
% COMBPile(:,:,9)=[ESTACA.NPP+ESTACA.NTempPOS, ESTACA.MPP+ESTACA.MTempPOS];
% COMBPile(:,:,10)=[ESTACA.NPP+ESTACA.NTempPOS+ESTACA.NTREMTIPO, ESTACA.MPP+ESTACA.MTempPOS+ESTACA.MTREMTIPO];
% COMBPile(:,:,11)=[ESTACA.NPP+ESTACA.NTempPOS+ESTACA.NTD, ESTACA.MPP+ESTACA.MTempPOS+ESTACA.MTD];
% COMBPile(:,:,12)=[ESTACA.NPP+ESTACA.NTempPOS+ESTACA.NTD+ESTACA.NTREMTIPO, ESTACA.MPP+ESTACA.MTempPOS+ESTACA.MTD+ESTACA.MTREMTIPO];
% Solo
COMBSoil(:,:,1)=SOLO.DeslPP+SOLO.DeslEMPSOLO+SOLO.DeslTempNEG;
COMBSoil(:,:,2)=SOLO.DeslPP+SOLO.DeslEMPSOLO+SOLO.DeslTempNEG+SOLO.DeslTREMTIPO;
COMBSoil(:,:,3)=SOLO.DeslPP+SOLO.DeslEMPSOLO+SOLO.DeslTempNEG+SOLO.DeslTD;
COMBSoil(:,:,4)=SOLO.DeslPP+SOLO.DeslEMPSOLO+SOLO.DeslTempNEG+SOLO.DeslTD+SOLO.DeslTREMTIPO;
COMBSoil(:,:,5)=SOLO.DeslPP+SOLO.DeslEMPSOLO;
COMBSoil(:,:,6)=SOLO.DeslPP+SOLO.DeslEMPSOLO+SOLO.DeslTREMTIPO;
COMBSoil(:,:,7)=SOLO.DeslPP+SOLO.DeslEMPSOLO+SOLO.DeslTD;
COMBSoil(:,:,8)=SOLO.DeslPP+SOLO.DeslEMPSOLO+SOLO.DeslTD+SOLO.DeslTREMTIPO;
COMBSoil(:,:,9)=SOLO.DeslPP+SOLO.DeslTempPOS;
COMBSoil(:,:,10)=SOLO.DeslPP+SOLO.DeslTempPOS+SOLO.DeslTREMTIPO;
COMBSoil(:,:,11)=SOLO.DeslPP+SOLO.DeslTempPOS+SOLO.DeslTD;
COMBSoil(:,:,12)=SOLO.DeslPP+SOLO.DeslTempPOS+SOLO.DeslTD+SOLO.DeslTREMTIPO;
